networkmanager: add missing dependency for config-extra.h in Makefile.am
Issue: LIN1019-7276

"""
In file included from ../NetworkManager-1.18.2/shared/systemd/nm-logging-stub.c:20:
../NetworkManager-1.18.2/shared/nm-default.h:120:10: fatal error: config-extra.h: No such file or directory
120 | #include "config-extra.h"
"""

Backport from Upstream:
[https://cgit.freedesktop.org/NetworkManager/NetworkManager/commit/?id=11d59de600e4af093db642279945d79efa5d1f33]
[https://cgit.freedesktop.org/NetworkManager/NetworkManager/commit/?id=deba9c4b86e49ff30e568818a72a2f170618d813]
[https://cgit.freedesktop.org/NetworkManager/NetworkManager/commit/?id=140619854e19ff84509eca9f845b9b0a90be4907]
[https://cgit.freedesktop.org/NetworkManager/NetworkManager/commit/?id=fd2e626b40effb354ecb363184b4dfc53f8dd3ce]

Signed-off-by: Liu Haitao <haitao.liu@windriver.com>