networkmanager: fix intermittent test-shared-general.c compile failures
Issue: LIN1019-7668

This fixes the following intermittent build failure:
In file included from ../NetworkManager-1.18.2/shared/nm-utils/tests/test-shared-general.c:22:                                                                          ../NetworkManager-1.18.2/shared/nm-default.h:120:10: fatal error: config-extra.h: No such file or directory
  120 | #include "config-extra.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.

The upstream commit needed to get rid of this issue *seems* to be 44c5331e29d8
("shared: move "shared/nm-utils/tests/test-shared-general" to
 "shared/nm-glib-aux/tests""). However, a lot dependencies are needed to bring
the necessary context for the patch to apply. To keep things simple, we go with
a minimally intrusive custom fix instead.

(LOCAL REV: NOT UPSTREAM) -- Not applicable, upstream out of maintenance

Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>