rocksdb: Fix build failure due to GCC9 deprecated-copy
Issue: LIN1019-1395

GCC9 introduce more stricter checks deprecated-copy and pessimizing-move, while
rocksdb uses -Werror and causes the following build error.

db/version_edit.h:178:33: error: implicitly-declared 'constexpr rocksdb::FileDescriptor::FileDescriptor(const rocksdb::FileDescriptor&)' is deprecated [-Werror=deprecated-copy]

utilities/persistent_cache/persistent_cache_util.h:51:23: error: moving a local object in a return statement prevents copy elision [-Werror=pessimizing-move]

(LOCAL REV: NOT UPSTREAM) -- sent to meta-openembedded 20190531

Signed-off-by: He Zhe <zhe.he@windriver.com>