pm-graph: parse separated cpu exec line
Issue: LIN1021-212

if cpu exec line was split into different line, there will be an error
when parse it:

  File "/usr/bin/sleepgraph", line 3165, in parseTraceLog
    proclist[name] = int(val[1])
IndexError: list index out of range

check this case and append to parse the unfinished line.

(LOCAL REV: NOT UPSTREAM) -- sent to meta-oe on 20210524

Signed-off-by: Liwei Song <liwei.song@windriver.com>