geoip: Update checksums
Issue: LIN9-6228

The upstream IP geolocation database binaries were updated, thus causing
a build failure when BB_NO_NETWORK ?= '0', due to checksum mismatching:

ERROR: geoip-1.6.9-r0 do_fetch: Checksum failure fetching http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz;apply=no;name=GeoIP-dat
ERROR: geoip-1.6.9-r0 do_fetch: Fetcher failure for URL: 'http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz;apply=no;name=GeoIP-dat'. Checksum mismatch!
...

Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>