lftp: fix PACKAGECONFIG[readline]
Issue: LIN9-1871

The --with-readline means check readline automatically, and will cause build
failures when there is /usr/include/readline:

ERROR: This autoconf log indicates errors, it looked at host include and/or library paths while determining system capabilities.

Use --with-readline=${STAGING_INCDIR}/.. to fix the problem. And also add
--with-readline=no when PACKAGECONFIG is not set for readline.

(LOCAL REV: NOT UPSTREAM) -- sent to oe on 20161028

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>