thin-provisioning-tools: switch branch master to main
Issue: LIN1019-5473

The upstream changed branch 'master' to 'main' which
causes the fetch issue:
ERROR: thin-provisioning-tools-0.8.5-r0 do_fetch: Network access
disabled through BB_NO_NETWORK

(LOCAL REV: NOT UPSTREAM) -- will send to meta-oe later

Signed-off-by: Haiqing Bai <Haiqing.Bai@windriver.com>